version: '2'
services:

  postgres:
    image: postgres:14.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: stub-password
      POSTGRES_DB: remindersdb
